elasticsearch:
  image: elasticsearch:latest
  command: elasticsearch -Des.network.host=0.0.0.0
  ports:
    - "9200:9200"
logstash:
  image: logstash:latest
  command: bash -c "plugin install logstash-input-beats && logstash -f /etc/logstash/conf.d/logstash.conf"
  volumes:
    - ./logstash/config:/etc/logstash/conf.d
  ports:
    - "5400:5400"
  links:
    - elasticsearch:elasticsearch
kibana:
  build: kibana/
  volumes:
    - ./kibana/config/kibana.yml:/opt/kibana/config/kibana.yml
  ports:
    - "5601:5601"
  links:
    - elasticsearch:elasticsearch
